package scd;

class Receptionist extends user {
    int R_id;
    String R_name;

    public Receptionist(int R_id, String R_name) {
        this.R_id = R_id;
        this.R_name = R_name;
    }

    void GiveAppoint() {
        System.out.println(R_name + " (Receptionist) gives an appointment.");
    }

    void GenerateBill(Billing bill) {
        System.out.println("Bill generated by " + R_name + " for patient ID: " + bill.P_id);
    }
}
